# Generated by Django 4.2.1 on 2023-05-20 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_remove_artistsong_artist_remove_artistsong_song_and_more'),
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborator_albums', to='artists.artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='primary_artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_album', to='artists.artist'),
        ),
    ]
