# Generated by Django 4.2.1 on 2023-05-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_remove_artistsong_artist_remove_artistsong_song_and_more'),
        ('albums', '0002_album_collaborators_album_primary_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='collaborators',
            field=models.ManyToManyField(blank=True, null=True, related_name='collaborator_albums', to='artists.artist'),
        ),
    ]
