# Generated by Django 4.2.1 on 2023-05-20 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlaylistSong',
        ),
    ]
