# Generated by Django 4.2.1 on 2023-06-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_unique_song_per_album'),
        ('playlists', '0003_delete_playlistsong'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='playlist_songs', to='songs.song'),
        ),
    ]
